name: Docker Push (development mode)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./frontend/Dockerfile
        push: true
        tags: mandarin3d/itsmejessicalee-docker:latest, mandarin3d/itsmejessicalee-docker:prod-${{ github.run_id }}
        build-args: |
          NGINX_CONF=./frontend/dev-nginx.conf

    - name: Send JSON to API endpoint
      run: |
        curl -X PUT "https://dockerapi.raavai.com/control/redeploy" \
        -H "Authorization: Bearer ${{ secrets.BEARER_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{"dc_name": "itsmejessicalee-dev", "dc_ip": "192.168.10.80", "dc_port": 5450, "dc_image": "mandarin3d/itsmejessicalee-docker"}'

  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./backend/Dockerfile
        push: true
        tags: mandarin3d/itsmejessicalee-docker-backend:latest, mandarin3d/itsmejessicalee-docker-backend:prod-${{ github.run_id }}

    - name: Send JSON to API endpoint
      run: |
        curl -X PUT "https://dockerapi.raavai.com/control/redeploy" \
        -H "Authorization: Bearer ${{ secrets.BEARER_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{"dc_name": "itsmejessicalee-backend-dev", "dc_ip": "192.168.10.185", "dc_port": 5451, "dc_image": "mandarin3d/itsmejessicalee-docker-backend"}'

